const path = require("path")

exports.createPages = async ({ graphql, actions, reporter }) => {
    // Destructure the createPage function from the actions object
    const { createPage } = actions;

    const result = await graphql(`
    query {
      allMdx {
        nodes {
            frontmatter {
              slug
            }
            id
          }
      }
    }
  `);

    if (result.errors) {
        reporter.panicOnBuild('🚨  ERROR: Loading "createPages" query');
    }

    // Create blog post pages.
    const posts = result.data.allMdx.nodes;
    // you'll call `createPage` for each result
    posts.forEach((post) => {
        // console.log(node);
        createPage({
            // The slug generated by gatsby-plugin-mdx doesn't contain a slash at the beginning
            // You can prepend it with any prefix you want
            path: post.frontmatter.slug,
            // This component will wrap our MDX content
            component: path.resolve(`./src/components/blogpage.jsx`),
            // You can use the values in this context in
            // our page layout component
            context: { id: post.id },
        })
    });
}